version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tdata_db
    environment:
      POSTGRES_DB: octobercms
      POSTGRES_USER: octo
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tdata_backend
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: octobercms
      DB_USERNAME: octo
      DB_PASSWORD: secret

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tdata_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"    # Проксируем Nginx:80 на локальный 5173
    restart: always

volumes:
  db_data:
